// place files you want to import through the `$lib` alias in this folder.
const icons = [
	'settings',
	'grade',
	'key',
	'open_with',
	'assistant_navigation',
	'stat_0',
	'dialogs',
	'stat_3',
	'point_scan',
	'radio_button_partial',
	'person',
	'health_and_safety',
	'eco',
	'emoji_objects',
	'public',
	'rocket_launch',
	'cruelty_free',
	'thunderstorm',
	'solar_power',
	'bedtime',
	'sunny',
	'skull',
	'tornado',
	'volcano',
	'hand_bones',
	'tibia',
	'deceased',
	'playing_cards',
	'helicopter',
	'call',
	'photo_camera',
	'shopping_cart',
	'shopping_basket',
	'local_library',
	'cut',
	'mic',
	'music_note',
	'flight',
	'two_wheeler',
	'snowmobile',
	'directions_boat',
	'agriculture',
	'local_taxi',
	'sports_esports',
	'sports_gymnastics',
	'sports_basketball',
	'roller_skating',
	'sports_football',
	'sports_baseball',
	'sports_soccer',
	'paragliding',
	'toys_fan',
	'fertile',
	'smart_toy',
	'headphones',
	'phone_iphone',
	'memory',
	'videogame_asset',
	'shield',
	'icecream',
	'luggage',
	'lunch_dining',
	'trip',
	'your_trips',
	'mop',
	'chair',
	'ac_unit',
	'yard',
	'sprinkler',
	'crib',
	'mode_heat',
	'child_care',
	'skillet',
	'tools_power_drill'
];

const legend = icons
	.map((value) => ({ value, sort: Math.random() }))
	.sort((a, b) => a.sort - b.sort)
	.map(({ value }) => value)
	.slice(0, 26)
	.map((value, i) => ({ character: String.fromCharCode(i + 65), icon: value }));

export default legend;
